In [7]:
file_obj = open('Desktop\sentences.txt', 'r')

In [9]:
print(file_obj.read())

In comparison to dogs, cats have not undergone major changes during the domestication process.
As cat simply catenates streams of bytes, it can be also used to concatenate binary files, where it will just concatenate sequence of bytes.
A common interactive use of cat for a single file is to output the content of a file to standard output.
Cats can hear sounds too faint or too high in frequency for human ears, such as those made by mice and other small animals.
In one, people deliberately tamed cats in a process of artificial selection, as they were useful predators of vermin.
The domesticated cat and its closest wild ancestor are both diploid organisms that possess 38 chromosomes and roughly 20,000 genes.
Domestic cats are similar in size to the other members of the genus Felis, typically weighing between 4 and 5 kg (8.8 and 11.0 lb).
However, if the output is piped or redirected, cat is unnecessary.
cat with one named file is safer where human error is a concern - one wrong use of the

In [11]:
? lower()

Object ` lower()` not found.


In [40]:
file_obj = open('Desktop\sentences.txt', 'r+')

In [41]:
string = file_obj.read().lower()

In [48]:
print(string)

in comparison to dogs, cats have not undergone major changes during the domestication process.
as cat simply catenates streams of bytes, it can be also used to concatenate binary files, where it will just concatenate sequence of bytes.
a common interactive use of cat for a single file is to output the content of a file to standard output.
cats can hear sounds too faint or too high in frequency for human ears, such as those made by mice and other small animals.
in one, people deliberately tamed cats in a process of artificial selection, as they were useful predators of vermin.
the domesticated cat and its closest wild ancestor are both diploid organisms that possess 38 chromosomes and roughly 20,000 genes.
domestic cats are similar in size to the other members of the genus felis, typically weighing between 4 and 5 kg (8.8 and 11.0 lb).
however, if the output is piped or redirected, cat is unnecessary.
cat with one named file is safer where human error is a concern - one wrong use of the

In [49]:
import re

In [60]:
list1 = re.split('[^a-z]', string)

In [62]:
while '' in list1: list1.remove('') 

In [64]:
word_frequencies = dict()

Словарь для подсчёта вхождения слов во всём тексте (не запускать) 

In [66]:
for i in range(len(list1)) : 
    if list1[i] in word_frequencies:
        word_frequencies[list1[i]] += 1
    else:
        word_frequencies[list1[i]] = 1

Словарь для индексация различных слов в тексте              

In [78]:
k = 0
for i in range(len(list1)) : 
    if list1[i] not in word_frequencies:
        word_frequencies[list1[i]] = k
        k += 1

Удаление всех элементов из словаря

In [76]:
for i in range(len(list1)) : 
    if list1[i] in word_frequencies:
        del (word_frequencies[list1[i]])

In [81]:
import numpy as np

In [84]:
num_of_sentencies = string.count('\n') + 1

In [85]:
print(num_of_sentencies)

22


In [126]:
num_of_words_in_sentencies = np.zeros((num_of_sentencies, k+1))

In [89]:
key_list = list(word_frequencies.keys())
val_list = list(word_frequencies.values())
print(key_list[val_list.index(1)]) 

comparison


In [ ]:
while n < num_of_sentencies :
    while '\n' not in string:
        if key_list[val_list.index(i)] in string:
            num_of_words_in_sentencies[n][i] += 1
            i += 1

In [98]:
list2 = string.split('\n')

In [99]:
print(list2)

['in comparison to dogs, cats have not undergone major changes during the domestication process.', 'as cat simply catenates streams of bytes, it can be also used to concatenate binary files, where it will just concatenate sequence of bytes.', 'a common interactive use of cat for a single file is to output the content of a file to standard output.', 'cats can hear sounds too faint or too high in frequency for human ears, such as those made by mice and other small animals.', 'in one, people deliberately tamed cats in a process of artificial selection, as they were useful predators of vermin.', 'the domesticated cat and its closest wild ancestor are both diploid organisms that possess 38 chromosomes and roughly 20,000 genes.', 'domestic cats are similar in size to the other members of the genus felis, typically weighing between 4 and 5 kg (8.8 and 11.0 lb).', 'however, if the output is piped or redirected, cat is unnecessary.', 'cat with one named file is safer where human error is a conc

In [ ]:
n = 0
while n < num_of_sentencies :
    
        for i in range(len(list2[m])) : 
            if list1[i] in list2[m]:
                num_of_words_in_sentencies[n][word_frequencies[list1[i]]] += 1
                print(i)
    n += 1   

In [116]:
num_of_sentencies = string.count('\n') + 1
for n in range(num_of_sentencies) :
    for i in range(len(word_frequencies)):
        if (key_list[val_list.index(i)]) in list2[n]:
            counter = list2[n].count(key_list[val_list.index(i)])
            num_of_words_in_sentencies[n][i] = counter

In [117]:
print(num_of_words_in_sentencies)

[[2. 1. 1. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [2. 0. 2. ... 0. 0. 0.]
 ...
 [3. 0. 0. ... 0. 0. 0.]
 [4. 0. 1. ... 0. 0. 0.]
 [2. 0. 1. ... 1. 1. 0.]]


In [104]:
print(word_frequencies)

{'in': 0, 'comparison': 1, 'to': 2, 'dogs': 3, 'cats': 4, 'have': 5, 'not': 6, 'undergone': 7, 'major': 8, 'changes': 9, 'during': 10, 'the': 11, 'domestication': 12, 'process': 13, 'as': 14, 'cat': 15, 'simply': 16, 'catenates': 17, 'streams': 18, 'of': 19, 'bytes': 20, 'it': 21, 'can': 22, 'be': 23, 'also': 24, 'used': 25, 'concatenate': 26, 'binary': 27, 'files': 28, 'where': 29, 'will': 30, 'just': 31, 'sequence': 32, 'a': 33, 'common': 34, 'interactive': 35, 'use': 36, 'for': 37, 'single': 38, 'file': 39, 'is': 40, 'output': 41, 'content': 42, 'standard': 43, 'hear': 44, 'sounds': 45, 'too': 46, 'faint': 47, 'or': 48, 'high': 49, 'frequency': 50, 'human': 51, 'ears': 52, 'such': 53, 'those': 54, 'made': 55, 'by': 56, 'mice': 57, 'and': 58, 'other': 59, 'small': 60, 'animals': 61, 'one': 62, 'people': 63, 'deliberately': 64, 'tamed': 65, 'artificial': 66, 'selection': 67, 'they': 68, 'were': 69, 'useful': 70, 'predators': 71, 'vermin': 72, 'domesticated': 73, 'its': 74, 'closest': 

In [105]:
print(list2)

['in comparison to dogs, cats have not undergone major changes during the domestication process.', 'as cat simply catenates streams of bytes, it can be also used to concatenate binary files, where it will just concatenate sequence of bytes.', 'a common interactive use of cat for a single file is to output the content of a file to standard output.', 'cats can hear sounds too faint or too high in frequency for human ears, such as those made by mice and other small animals.', 'in one, people deliberately tamed cats in a process of artificial selection, as they were useful predators of vermin.', 'the domesticated cat and its closest wild ancestor are both diploid organisms that possess 38 chromosomes and roughly 20,000 genes.', 'domestic cats are similar in size to the other members of the genus felis, typically weighing between 4 and 5 kg (8.8 and 11.0 lb).', 'however, if the output is piped or redirected, cat is unnecessary.', 'cat with one named file is safer where human error is a conc

In [106]:
print(num_of_words_in_sentencies[0][3])

1.0


In [107]:
print(word_frequencies['it'])

21


In [118]:
print(num_of_words_in_sentencies[1][21])

2.0


In [110]:
print(list2[1])

as cat simply catenates streams of bytes, it can be also used to concatenate binary files, where it will just concatenate sequence of bytes.


In [119]:
print(num_of_words_in_sentencies[0][0])

2.0


In [123]:
list3[num_of_sentencies]
for l in range(num_of_sentencies):
    list3[l]=re.split('[^a-z]', list2[l])

NameError: name 'list3' is not defined

In [127]:
num_of_sentencies = string.count('\n') + 1
for n in range(num_of_sentencies) :
    for i in range(len(word_frequencies)):
        if (key_list[val_list.index(i)]) in re.split('[^a-z]', list2[n]):
            counter = (re.split('[^a-z]', list2[n])).count(key_list[val_list.index(i)])
            num_of_words_in_sentencies[n][i] = counter

In [129]:
print(num_of_words_in_sentencies[1][21])


2.0


In [130]:
print(num_of_words_in_sentencies)

[[1. 1. 1. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 [0. 0. 2. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [0. 0. 1. ... 1. 1. 0.]]


In [131]:
import scipy

In [133]:
import numpy
res = num_of_words_in_sentencies.transpose()

In [134]:
print(res[0][2])

0.0


In [135]:
print(num_of_words_in_sentencies)

[[1. 1. 1. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 [0. 0. 2. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [0. 0. 1. ... 1. 1. 0.]]


In [175]:
import scipy.spatial.distance

dists = []
for j in range(num_of_sentencies):
    dists.append(scipy.spatial.distance.cosine(num_of_words_in_sentencies[0,:], num_of_words_in_sentencies[j,:]))

In [176]:
print(dists)

[0.0, 0.9527544408738466, 0.8644738145642124, 0.8951715163278082, 0.7770887149698589, 0.9402385695332803, 0.7327387580875757, 0.9258750683338899, 0.8842724875284311, 0.9055088817476932, 0.8328165362273942, 0.8804771390665607, 0.8396432548525454, 0.8703592552895671, 0.8740118423302576, 0.9442721787424647, 0.8406361854220809, 0.956644501523794, 0.9442721787424647, 0.8885443574849294, 0.8427572744917122, 0.8250364469440588]


In [172]:
del(dists[5])

In [174]:
index, max_value = min(enumerate(dists), key=lambda i_v: i_v[1])
print(index)

3


In [166]:
print(res[4])

[1. 0. 0. 1. 1. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
